Arreglo de principio Tell, don't ask
alvaromartin47-rgb/tp2-algo3-fiuba pull request #6
Opened 2021-07-15 22:58 UTC by martindelcastillo

2021-07-15 23:31 UTC, alvaromartin47-rgb commented on src/main/java/edu/fiuba/algo3/modelo/Mapa.java
> +            if (pais.compararNombre(unNombrePais)) return pais;
Me parece mejor un:
`if (pais.compararNombre(unNombrePais)) return pais;`

2021-07-15 23:51 UTC, alvaromartin47-rgb commented on src/main/java/edu/fiuba/algo3/modelo/Pais.java
> +    public boolean compararNombre(String unNombrePais) {
Mismo caso anterior

2021-07-15 23:54 UTC, alvaromartin47-rgb requested changes
Habría que borrar además el método nombre() de Pais.

2021-07-16 00:09 UTC, martindelcastillo commented on src/main/java/edu/fiuba/algo3/modelo/Mapa.java
> +            if (pais.compararNombre(unNombrePais)) return pais;
Si bien en tema de implementación es lo mismo, creo que llamarlo "coincideNombre" medio que sigue rompiendo el Tell, don't ask, porque le estoy preguntando si coincide el nombre, mientras que con "compararNombre" le estoy diciendo que lo haga, y lo dejo lugar a pregunta.

2021-07-16 01:47 UTC, OliGruss approved these changes

2021-07-16 01:55 UTC, alvaromartin47-rgb commented
Muchachos, para ambos, en mi opinion esto no rompe el principio que dicen. El tell dont ask es para casos donde la lógica es mas compleja y hay muchos get a otra clase, entonces buscas la forma de delegar. Si esto rompe ese principio entonces no se podría tener ningún getter de nada, el nombre es algo a lo que se suele acceder además porque es algo muy simple. Acá la modificación básicamente es lo mismo lo que me plantean ustedes. De todas formas la voy a aprobar y mañana le preguntamos a Joaquin.

2021-07-16 01:56 UTC, alvaromartin47-rgb approved these changes

2021-07-16 02:03 UTC, merged